= DGGS Persistent Identifiers

This web page provides information on a range of Discrete Global Grid Systems (DGGS)-related resources.

This web page provides human-readable information for DGGS resources when persistent identifiers for them are resolved, i.e. when a person clicks on web addresses used to identify individual DGGSes. Machine-readable information either is, or hopefull soon will be, available when machines resolve DGGS persistent identifiers and ask for data.

This page is reached when someone tries to resolve the register of, or parent of, all individual DGGS resources, i.e. the top-parent list of them all.

== Resources

This location is the register - managed list of - the following child lists:

* https://kurrawong.github.io/dggs/def[Definitional Objects]
** DGGS-related ontologies, models, vocabularies and profiles
* https://kurrawong.github.io/dggs/systems[Systems]
** different DGG Systems

== More Information

Discrete Global Grid System research is conducted by https://kurrawong.ai[KurrawongAI], an Australian-based tech company, following work done by the https://www.ogc.org/[Open Geospatial Consortium] to standardise the specifications/interfacesfunctions of DGGSes, for example the "abstract specification" for them: https://docs.ogc.org/as/20-040r3/20-040r3.html[Topic 21 - Discrete Global Grid Systems - Part 1 Core Reference system and Operations and Equal Area Earth Reference System].

Contact KurrawongAI on:

info@kurrawong.ai +
https://kurrawong.ai
